# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "球球"
description: > # this means to ignore newlines until "email:"
   球球，咱们的blog

email: hyy12345678@gmail.com
#blog logo
logo: "/assets/images/xiaoguai.jpg"
# blog cover
cover: "/assets/images/mainpage_bg.jpg"

name: '大乖和小乖'
author: '大乖和小乖'
author_image: "/assets/images/daguai.jpg"

paginate:	5

url: "http://hyy12345678.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/hyy12345678
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/hyy12345678
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
